### ISSUE TITLE
Plotting 2D section

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#390] opened 2020-04-22 12:33 UTC
When i plot 2D section,i set the extent of modeling area,as a cuboid in the previous program,so the top of the 2D section looks like flat,and the top of section  does't show the uneven character of the terrain,so how can i make it,thank you.
![Figure_3](https://user-images.githubusercontent.com/60054308/79982146-67f2f700-84d8-11ea-97cf-cd4dde050930.png)

**Comment by wh19971014** [comment] 2020-04-22 13:03
And another trouble:i want to plot a 2D section of selected direction, it occured the error "the xy values of the first point must be smaller than second(fix soon)",but the endpoint's X Y values at both ends of the profile can't be changed.Can't the profile in this direction be drawn successfully?
![1](https://user-images.githubusercontent.com/60054308/79985104-b30f0900-84dc-11ea-8a49-074a884338b1.png)
![2](https://user-images.githubusercontent.com/60054308/79985125-bacead80-84dc-11ea-88a8-215dd9e4c4d9.png)

**Comment by AlexanderJuestel** [comment] 2020-04-22 13:11
Hello, 

please provide more information (e.g. code) on how you plotted the section? Have you activated the topography? 

For your second issue, you should look at how your custom section is defined and check your coordinates (if you have defined it at all or rather just want to plot along the x or y axis).

**Comment by wh19971014** [comment] 2020-04-22 13:44
Hi, @AlexanderJuestel ,here are the code and file ,may you help me see if the code is not true somewhere.
[Code and file.zip](https://github.com/cgre-aachen/gempy/files/4516437/Code.and.file.zip)

**Comment by Japhiolite** [comment] 2020-04-22 14:05
Concerning the assertion error, there methods are updated in PR #382  and will be available in the future.

**Comment by wh19971014** [comment] 2020-04-23 01:21
@Japhiolite  ,Hi. When i add Fault12,it occured error "Surface level must be within volume data range",but the coordinate value of data point is smaller than the extent i set,and when i delete the  data of Fault12,the code runs successfully,i am confused.
![1](https://user-images.githubusercontent.com/60054308/80048750-a2de4480-8543-11ea-91a5-0ae82c332ea3.png)
![2](https://user-images.githubusercontent.com/60054308/80048755-a7a2f880-8543-11ea-837a-d9d8ff20a22b.png)
![3](https://user-images.githubusercontent.com/60054308/80048758-aa055280-8543-11ea-975b-7d36f372e821.png)
![4](https://user-images.githubusercontent.com/60054308/80048766-ae317000-8543-11ea-8f8b-3400a554eda9.png)

**Comment by wh19971014** [comment] 2020-04-23 06:46
Hi, @AlexanderJuestel .I examine  how my custom section is defined and check my coordinates,they all meet the rules,right.And X Y value of the first point i set earlier is bugger than the second point,the code runs successfully.Strange,and there are my uploading code and file on the earlier comment.

**Comment by Japhiolite** [comment] 2020-04-23 07:01
@wh19971014 the last surface point you add for `Fault12` has exactly the same X coordinate as the model boundary. I assume this may be the error, as it should be inside the model domain. Try to reduce the X coordinate for the point to 44500 for example.

**Comment by wh19971014** [comment] 2020-04-23 08:14
Hi, @Japhiolite ,I have a trouble in the first comment of this question about( plotting a 2D section of selected direction, it occured the error "the xy values of the first point must be smaller than second(fix soon)"),and please see penult comment,do you have idea,thank you very much.

**Comment by Japhiolite** [comment] 2020-04-23 08:37
As I mentioned before, the function in question will be updated in a future version of GemPy. 
The assertion error `the xy values of the first point must be smaller than the second` is intended to be raised in the current version of GemPy if a section's starting point is not smaller or equal to its end point.

Your options are:  
* change your section to satisfy this criterion.   
* use the branch `development_janN`  
* wait for the function to be updated  

Was the problem with your Fault12 solved?

**Comment by wh19971014** [comment] 2020-04-23 08:43
Yes,the problem of Fault12 was solved,thank you very much.I don't know what's "development_janN",what does it do,is there example code about it?

**Comment by Japhiolite** [comment] 2020-04-23 08:45
If you use GemPy directly from source (i.e. here from the repository), you can switch between branches.  
This is *not* available, if you installed GemPy via pip (what I assume you did?)

**Comment by wh19971014** [comment] 2020-04-23 10:04
Hi, @Japhiolite ,I changed the direction of the Y-axis,so it goes in the positive direction.The range of the set cuboid has changed,and the X、Y coordinate value of the first point of the profile is less than the second point,but the same error still occurs,very strange.
![1](https://user-images.githubusercontent.com/60054308/80086828-d7c2b980-858c-11ea-9fbf-a9839556fdb2.png)
![2](https://user-images.githubusercontent.com/60054308/80086847-dee9c780-858c-11ea-9cc7-21181ddd2d3d.png)
![3](https://user-images.githubusercontent.com/60054308/80086858-e27d4e80-858c-11ea-807f-115e11a77645.png)
![5](https://user-images.githubusercontent.com/60054308/80086867-e610d580-858c-11ea-9d7d-59e3d49e4039.png)

**Comment by Japhiolite** [comment] 2020-04-23 10:34
Clever/Cheecky way of trying to solve this. And interesting that the software doesn't respond accordingly (or doesn't get fooled). 
I think, the strike of the section is important. For instance, in this quick sketch, any profile going through the "Ok" quadrants of a circle we imagine in our model (like the green line) will work (so everything Striking North-South to East-West, rotating clockwise).
Any section which goes through the  "Not ok" quadrants (like the orange line) will raise this assertion error. So apparently setting a space coordinate to negative values does not do the trick.

![image](https://user-images.githubusercontent.com/13364692/80089786-be0a7d80-855e-11ea-909e-f865a5337798.png)

**Comment by wh19971014** [comment] 2020-04-23 12:30
Hi, @Japhiolite .I don't understand what changing the function accordingly means ,and installing GemPy via pip are different installing GemPy via conda.
And you upload a source code,what does it do.

**Comment by wh19971014** [comment] 2020-04-23 12:31
Hi, @Japhiolite .I don't understand clearly what changing the function accordingly means ,and installing GemPy via pip are different installing GemPy via conda?
And you upload a source code,what does it do.

**Comment by Japhiolite** [comment] 2020-04-23 12:37
In your installed version of Gempy:  
1. Navigate to the file `grid_types.py' the path should be: F:\Anaconda\lib\site-packages\gempy\core\grid_modules\grid_types.py  and open it.
2. In there is a function called `interpolate_zvals_at_xy`.  
3. Replace the function with the one I provided here: https://gist.github.com/Japhiolite/f8eb5fd5d9b84348dac6e8071652fcee  
4. save and close the file  
5. restart your kernel/notebook.  
6. now you should not get the assertion error anymore.

**Comment by wh19971014** [comment] 2020-04-23 14:16
Hi, @Japhiolite . I replace Replace the function with the one you provided ,when then code runs on the step "gp.plot.plot_section_by_name(geo_model, 'section1')",it did't occured error ,but there is no 2D section here, and it seems that the command did't execute the code i wrote to form the 2D section,Strange.
![1](https://user-images.githubusercontent.com/60054308/80109340-f4241d80-85af-11ea-9553-95d352824507.png)

**Comment by Japhiolite** [comment] 2020-04-23 15:34
Difficult to judge by the warnings you show in the screenshot. Your computed model already seems to be faulty/fishy, hence the "Ill-conditioned matrix" warning.

**Comment by wh19971014** [comment] 2020-04-24 01:28
Hi， @Japhiolite .Here is a ZIP package of code and needed file,may you help me run the code when replacing the function to look at how's the answer,thank you so much.
[Code and file.zip](https://github.com/cgre-aachen/gempy/files/4526135/Code.and.file.zip)

**Comment by Japhiolite** [comment] 2020-04-24 06:43
Hi @wh19971014 I had a look at your code, but have to say that I cannot help you at the moment, as your notebook is not running.  
One reason for this is: your surface data lies outside your model. The z dimension of your model is [-3000, 1800]. The z values of your surfaces are z=2500.  So you should try fixing this, maybe it helps.

Further (but unrelated to the point above), you should have a look at your theano installation, as your compilers seem to need fixing
![image](https://user-images.githubusercontent.com/13364692/80182077-5f98da00-8606-11ea-8d61-14da59c35014.png)  

Lastly, I have to say that it is difficult to follow through your notebook. Therefore I ask, that if you provide your code / notebook, please make sure that it is understandable and also runs until the problem you wrote an issue for. Otherwise, it is difficult to reproduce what is going on, and errors like above (data out of model bounds) would not occur.  

Speaking of issues: It saves a lot of back-and-forth, and thus saves all of us a lot of time, if certain things are covered (for example _Description_ of the problem, and important, a description _how to reproduce_ an error). There are multiple examples on "How to write good issues", for example: https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md  

Please don't take this as condescending, but a properly written issue helps me/us to help you.

**Comment by wh19971014** [comment] 2020-04-29 13:49
Hi, @Japhiolite .If I want to run the code on Ubuntu system,how can I replace the function  called **interpolate_zvals_at_xy**with the one you provided at your earlier comment,the web site is  https://gist.github.com/Japhiolite/f8eb5fd5d9b84348dac6e8071652fcee.Thank you very much.

**Comment by Japhiolite** [comment] 2020-04-29 13:58
See comment https://github.com/cgre-aachen/gempy/issues/390#issuecomment-618377567

**Comment by Japhiolite** [comment] 2020-05-05 13:47
Any updates here @wh19971014 ?
If the workaround worked, we can close the Issue.

**Closed** 2020-05-10 05:33 UTC

**Comment by AlexanderJuestel** [comment] 2020-05-15 09:52
Hello, 

I would just like to confirm that the fix mentioned by @Japhiolite is working. Thanks for that!
