### ISSUE TITLE
Limit the fault extension length

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#369] opened 2020-04-10 01:44 UTC
Hello, i have a question:how to limit the fault range? For example,i want to limit the length of the extension of the fault along the way its goes.Thank you.

**Comment by javoha** [comment] 2020-04-10 07:28
Dear @wh19971014 ,

first a couple of general things: You opened this issue which looks like a duplicate of #359. Also you created two identical issues (#362 and #367) for another problem you have . While we are always eager to help, we all do not work on this project full-time and have other things on our lists. We come back to answering questions regularly, but we will sometimes need more time than just 2 days. So please don't create duplicate issues. I will now delete the duplicates (#359 and #362).

Apart from that it is really helpful if you follow the template for issues: There are many well written, well documented issues that show how this process works best. Please add more context to your questions and describe what you have tried to solve it. This makes it alot easier for us to provide help.

Regarding your problem: As far as I know there is a function to create finite faults by cutting the extent in form of an ellipsoid. This is still worked on and we have to check it again - we will let you know as soon as there are news.

Best wishes,
Jan

**Comment by wh19971014** [comment] 2020-04-26 11:59
Hi, @javoha .Can the function of limit the extension length of strike of the fault be used,I'm in a hurry to use it,thank you very much,looking forward your reply soon.

**Comment by wh19971014** [comment] 2020-05-09 08:19
Hi, @javoha , @flohorovicic 
do you have idea now to limit the extension length along strike dirction of the fault,I am in a hurry to get that function,thank you  very much.

**Closed** 2020-05-10 05:33 UTC
Labels: question
