### ISSUE TITLE
Limit the extension length along strike direction of the fault

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#410] opened 2020-05-10 05:43 UTC
**What is your question?**
**First question:**Because the length of a fault is short along its strike direcyion,but when computing the data to make 3D model,the extension length of the fault is more than actual length,do you have idea now to limit the extension length along strike direction of the fault,I am in a hurry to get that function,thank you very much.
**Another question:**Whether this phenomenon is related to global interpolation of GemPy,and what does global interpolation mean,I don't understand that clearly.

**Comment by AlexanderJuestel** [comment] 2020-05-10 06:00
Duplicate of #369

**Comment by wh19971014** [comment] 2020-05-10 06:13
Hi, @AlexanderJuestel 
Yeah,I asked the same question early time, but there is no solution .

**Comment by AlexanderJuestel** [comment] 2020-05-10 06:21
Hi @wh19971014,

There is no need in opening multiple issues with the same content as we see which issues are open. GemPy is an open source project so not everyone may be checking these issues regularly or has time to answer them. Many of our contributors were busy with the EGU last week for instance. 

But regarding your question: what have you tried so far? Can you provide code with your tests? Where did you encounter issues? Did you have a look at the GemPy documentation or at the code itself? What are your current ideas to fix the issue? 

Have a good Sunday
Alex

**Closed** 2020-05-10 07:09 UTC

**Comment by AlexanderJuestel** [comment] 2020-05-14 13:09
Hello, 

without reopening the issue I would like to mention that you can limit the ellipsoid of your fault with:

`geo_model.faults.df['isFinite'][['NameofFault']] = True`

According to our programmers, this will limit any offset along the fault to extent of your fault interfaces. However, your fault will still be drawn infinetely in 3D. I also added a little drawing below. I hope that helps.

![image](https://user-images.githubusercontent.com/45469915/81938120-cd786600-95f4-11ea-82cf-dd31ccda3ae5.png)
(Image Source: http://www.files.ethz.ch/structuralgeology/JPB/files/English/3extsyst.pdf)

**Comment by Leguark** [comment] 2020-05-14 13:16
use `geo_model.set_is_finite_fault()` !

**Comment by wh19971014** [comment] 2020-05-14 13:58
Hello, @AlexanderJuestel 
it can Limit the extension length along strike direction of the fault，not only along the extending's depth

**Comment by AlexanderJuestel** [comment] 2020-05-14 14:04
That is correct. However, the depth of your fault is limited by the model extent and by the age relationships between faults. So a younger fault will cross cut and offset an older fault.

**Comment by wh19971014** [comment] 2020-05-14 14:21
Hi, @AlexanderJuestel 
Please see the following photo,thank you very much.
![up](https://user-images.githubusercontent.com/60054308/81945908-44cbeb00-9631-11ea-82a8-db9111684027.png)

**Comment by AlexanderJuestel** [comment] 2020-05-15 09:51
Dear @wh19971014, 

currently, there is no functionality implemented in GemPy to solve the problem your are describing. However, there may be workarounds to do it outside the GemPy environment. You could for instance extract the coordinates of the fault trace as array and then plot the desired amount of points.

Best regards
Alex
