### ISSUE TITLE
How to fill lithology

### ISSUE THREAD

**Issue by wh19971014** [cgre-aachen/gempy#362] opened 2020-04-08 13:55 UTC
Hello, i want to know how to fill lithology between different layer rocks.

**Comment by javoha** [comment] 2020-04-09 06:41
Hello @wh19971014 ,

I am not sure if I fully understand your question: The input data points you give Gempy represent surfaces (layer boundaries). The space between any two surfaces will be filled with the lithology that was assigned to the lower boundary surface. All the remaininig space that is "older" (often below) the oldest defined surface (old refering to how you order your series) will be filled with "basement". The top of your model will be limited by either a topography or your model extent. So there will never be just empty space (or at least there shouldnt be). Maybe this answers your question? Otherwise please ellaborate a little bit or provide an example of the exact problem.

Cheers,
Jan

**Comment by javoha** [comment] 2020-04-10 07:30
Closed as duplicate of #367

**Closed by javoha** 2020-04-10 07:30 UTC
Labels: question
