### ISSUE TITLE
A UserWarning: Surfaces not computed due to: marching_cubes_lewiner() got an unexpected keyword argument 'mask'

### ISSUE THREAD

**Issue by viviengis** [cgre-aachen/gempy#216] opened 2019-09-21 10:37 UTC
When I am running this "gp.compute_model(geo_model, compute_mesh=True)" in Ch1-1_Basics lines [19], I find a warinning : "C:\ProgramData\Anaconda3\lib\site-packages\gempy\core\solution.py:258: UserWarning: Surfaces not computed due to: marching_cubes_lewiner() got an unexpected keyword argument 'mask'
  warnings.warn('Surfaces not computed due to: ' + str(e))". It will affect exporting to vtk. How can I   deal wiht it？

**Comment by Leguark** [comment] 2019-09-27 12:44
This warning is raising when you do not install my folked version of scikit-image (I am waiting for a pull request into the main repo). Basically what my changes does is to intersect the surfaces accordingly to the unconformities.

If you want to have the layers terminating on each other simply run:
pip install git+git://github.com/Leguark/scikit-image@master

Otherwise the layers will be infinite but in principle the export to vtk should work without further issues.

**Comment by bistek** [comment] 2019-09-27 16:35
Hello, I got similar errors. I am running GemPy on Windows 10 with all the components updated on September 23rd. I tried to:

`pip install git+git://github.com/Leguark/scikit-image@master`

but I got a very verbose error related to:

`ERROR: Failed building wheel for scikit-image`

Any idea?

Thanks very much!

**Comment by bistek** [comment] 2019-09-27 17:07
Similar errors come out also when running the following tutorials:

ch1-6_CreatingModels

ch1-8_Onlap_relations

ch2-1-Gravity

**Comment by viviengis** [comment] 2019-09-29 02:19
> This warning is raising when you do not install my folked version of scikit-image (I am waiting for a pull request into the main repo). Basically what my changes does is to intersect the surfaces accordingly to the unconformities.
> 
> If you want to have the layers terminating on each other simply run:
> pip install git+git://github.com/Leguark/scikit-image@master
> 
> Otherwise the layers will be infinite but in principle the export to vtk should work without further issues.

**Comment by viviengis** [comment] 2019-09-29 02:26
I had installed the scikit-image, but the issue was not resolved. Then I revised solution.compute_surface_regular_grid, changing classic=False to classic=True, and the surfaces can be computed.

**Comment by bistek** [comment] 2019-09-29 07:48
Hello, when I try to install the custom scikit as suggested, I get:

ERROR: Failed building wheel for scikit-image

Do you have suggestions?

Thanks!!

**Comment by Leguark** [comment] 2019-09-30 08:33
@viviengis yes, I thought I had fixed the try and excepts to do so but you found the code that gives problems. It would be great if you take a look to the current master branch if still have the problem and if not send a pull request.

@bistek  Not from the top of my head. It may be that you need to have cython installed in your environment but I am not sure.

I thought I had deal with the bug even when the modify scikit-image was not installed. It may be that it is not on the pip release yet.

This week I am at a conference but I will try to check it out soon and probably release a hotfix. Thank you for reporting it!

**Comment by bistek** [comment] 2019-09-30 14:27
Hello, it looks like I cannot install the modified scikit-image. I have un up-to-date conda with all required packages for gempy (including cython), but when I try to install with:

`pip install git+git://github.com/Leguark/scikit-image@master`

I get this error (I copy all since I cannot really understand what is going on):

`(base) C:\Users\bistek>pip install git+git://github.com/Leguark/scikit-image@master`
`Collecting git+git://github.com/Leguark/scikit-image@master`
`Cloning git://github.com/Leguark/scikit-image (to revision master) to c:\users\bistek\appdata\local\temp\pip-req-build-xie73893`
`Running command git clone -q git://github.com/Leguark/scikit-image 'C:\Users\bistek\AppData\Local\Temp\pip-req-build-xie73893'`
`Running command git submodule update --init --recursive -q`
`Requirement already satisfied: networkx>=2.0 in c:\anaconda3\lib\site-packages (from scikit-image==0.16.dev0) (2.3)`
`Requirement already satisfied: pillow>=4.3.0 in c:\anaconda3\lib\site-packages (from scikit-image==0.16.dev0) (6.1.0)`
`Requirement already satisfied: imageio>=2.0.1 in c:\anaconda3\lib\site-packages (from scikit-image==0.16.dev0) (2.5.0)`
`Requirement already satisfied: PyWavelets>=0.4.0 in c:\anaconda3\lib\site-packages (from scikit-image==0.16.dev0) (1.0.3)`
`Requirement already satisfied: decorator>=4.3.0 in c:\anaconda3\lib\site-packages (from networkx>=2.0->scikit-image==0.16.dev0) (4.4.0)`
`Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from imageio>=2.0.1->scikit-image==0.16.dev0) (1.16.5)`
`Building wheels for collected packages: scikit-image`
`Building wheel for scikit-image (setup.py) ... error`
`ERROR: Command errored out with exit status 1:`

- then a lot of errors in red here, then:

`ERROR: Failed building wheel for scikit-image`
`Running setup.py clean for scikit-image`
`Failed to build scikit-image`
`Installing collected packages: scikit-image`
`Found existing installation: scikit-image 0.15.0`
`Uninstalling scikit-image-0.15.0:`
`Successfully uninstalled scikit-image-0.15.0`
`Running setup.py install for scikit-image ... error`
`ERROR: Command errored out with exit status 1:`

- then again a lot of error messages in red, then:

`Rolling back uninstall of scikit-image`
`Moving to c:\anaconda3\lib\site-packages\scikit_image-0.15.0-py3.7.egg-info from c:\anaconda3\lib\site-packages\~cikit_image-0.15.0-py3.7.egg-info`
`Moving to c:\anaconda3\lib\site-packages\skimage from c:\anaconda3\lib\site-packages\~kimage`
`Moving to c:\anaconda3\scripts\skivi-script.py from C:\Users\bistek\AppData\Local\Temp\pip-uninstall-9rzj1x6_\skivi-script.py`
`Moving to c:\anaconda3\scripts\skivi.exe from C:\Users\bistek\AppData\Local\Temp\pip-uninstall-9rzj1x6_\skivi.exe`

Do you have suggestions?

Shall I uninstall the regular scikit-image before installing the modified version?

Thanks very much!

**Comment by viviengis** [comment] 2019-10-05 09:13
@bistek  Sorry, I did not encounter the mentioned problem. I installed python3.7 and gempy2.0, and other Python packages. Then, I installed scikit-image with : pip install scikit-image, and it was successfully.

**Comment by bistek** [comment] 2019-10-07 16:11
@viviengis I have the standard scikit-image installed with pip

```
(base) C:\Users\bistek>pip show scikit-image
Name: scikit-image
Version: 0.15.0
Summary: Image processing routines for SciPy
Home-page: https://scikit-image.org
Author: None
Author-email: None
License: Modified BSD
Location: c:\anaconda3\lib\site-packages
Requires: scipy, matplotlib, networkx, pillow, imageio, PyWavelets
Required-by:
```

But I get the errors above with

`gp.compute_model(geo_model, compute_mesh=True)`

So I tried to install the scikit-image version by @Leguark with

`pip install git+git://github.com/Leguark/scikit-image@master`

But I was not able, since I get the other errors listed above.

So I am in a sort of dead end.

**Comment by Leguark** [comment] 2019-10-08 06:54
I am surprised that with the official scikit-image does not work (but without surfaces intersection). I will take a look this afternoon. Thank you to both of you for narrow down the bug

**Comment by Leguark** [comment] 2019-10-08 10:55
I have installed the pip version of gempy and the pip version of scikit-image and I get a warning:

/anaconda3/envs/gempy/lib/python3.7/site-packages/gempy/core/solution.py:253: UserWarning: Attribute error. Using non masked marching cubesmarching_cubes_lewiner() got an unexpected keyword argument 'mask'

but it gives me the surfaces as expected. Is it possible that you do not have the last version of GemPy? 

Can you try:

pip install --upgrade --force-reinstall gempy

**Comment by bistek** [comment] 2019-10-08 11:21
Hello, sorry if I was not crystal clear...

- I have the latest GemPy directly downloaded from GIT, so maybe even more recent than the one I would get with PIP.

- If I do not try to crosscut the surfaces it works with the standard scikit-image. However I really would like to crosscut them. So I tried to install the custom scikit-image, but I am not able since I get a lot of errors when I try

pip install git+git://github.com/Leguark/scikit-image@master

Thanks!

**Comment by Leguark** [comment] 2019-10-08 12:12
alright, sorry for that. I did not know what you were trying to do. Okay, then the problem is the installation of the custom version of scikit-image gattcha. Honestly, I am not sure if I can help you too much there since it is a problem with compiling scikit image.

Maybe you can try to clone the repo (my fork) and install it with:

python setup.py install

If does not work maybe, we get better error messages

In my enviroments (MacOS and Linux) this command (pip install git+git://github.com/Leguark/scikit-image@master) works properly

**Comment by bistek** [comment] 2019-10-08 13:39
I suppose I'll have to uninstall the standard scikit-image, before installing yours. Correct?

BTW, I have Windows 10. Maybe there is some component or library in scikit-image that must be compiled or that is somehow OS-dependent? Could this be the problem?

Thanks!

**Comment by Leguark** [comment] 2019-10-09 06:13
yes, it is better to uninstall the main scikit-image.

scikit image is usually compiled. If I understand it right, the official package gets compiled on the cloud to pretty much all the systems so when pip is used we only have to download it.

On the other hand, if you clone it and modify something, it is necessary to compile it with Cython that I think that depends on a gcc compiler.

Now, windows does not come with a gcc compiler installed so this raise many problems (more than MacOs and Linux anyways) with path environments with many python packages that require compilers. That is pretty much all the insight I can give you.

Honestly, I made the pull request with this feature over 6 months ago. I did not expect to take this long. I will try to give it an extra thought to see if I am able to add the feature as a code injection from GemPy but it is really an unfortunate situation. Sorry for that.

**Comment by bistek** [comment] 2019-10-13 14:16
Dear @Leguark,

1) I uninstalled the standard scikit-image

2) I cloned your custom scikit-image repo

3) finally I tried to install it with `python setup.py install`. Unfortunately I got this error:

`error: Command "gcc -g -shared build\temp.win-amd64-3.7\Release\skimage\restoration\_nl_means_denoising.o -LC:\Anaconda3\libs -LC:\Anaconda3\PCbuild\amd64 -lpython37 -lvcruntime140 -o build\lib.win-amd64-3.7\skimage\restoration\_nl_means_denoising.cp37-win_amd64.pyd -fopenmp" failed with exit status 1`

I attach a complete log of the terminal (maybe it tell you something useful).

[my_error_log.log](https://github.com/cgre-aachen/gempy/files/3721839/my_error_log.log)

This is very frustrating because without the custom scikit-image I cannot properly cut faults etc.

Thank you very much!

**Comment by bistek** [comment] 2019-10-13 17:01
Additional problem: in my test-model (that is now behaving-much better) I've set some faults as finite, but they come out as infinite. Is this because of the problem with scikit-image?
Thanks again.

**Comment by Leguark** [comment] 2019-10-14 07:39
1) Mmm for the scikit image install problem try to delete all folders on the skimage folder except the measure that is the one that contains the marching cube algorithm. I am going to write the skimage people again and if I get no answer I will give it a go to implement it into gempy somehow

2) For the second question, right now the finite faults are in a veeeery early dev stage. The surface in vtk will look infinite, only the area that is offset is finite. And definitely will only work with my skimage. I make the task and I will try to fix it for the next release of gempy but will take 1 or 2 months.

**Comment by bistek** [comment] 2019-10-14 15:49
Hello @Leguark ,

1) shall I delete the reference to the folders from the setup.py script (at the congig.add lines), or physically from the skimage folder? And in this case I still have to uninstall the standard scikit-image?

2) faults - all clear. Does the vtk surface have an offset property recorded on the nodes? In this way you could in theory find the tipline as the zero offset contour, correct?

Thanks very much!

**Comment by bistek** [comment] 2019-10-16 06:47
Dear @Leguark, let me see if I understand... the custom scikit differs from the standard just in the measure folder? If all the code here is Python, not compiled, can I just copy your measure folder into the standard scikit?

Thanks!

**Comment by Leguark** [comment] 2019-10-16 06:57
The problem is that the function is written in Cython so therefore is compiled. The compilation happens during the installation. However, I think the error you get is from a function that has nothing to do with marching cubes

**Comment by bistek** [comment] 2019-10-16 07:34
Ok. So shall I download / compile / install just the measure folder leaving the original scikit (the one I get with pip) in place, or after uninstalling it? I’ll try the first option...

Thanks!!!

**Comment by bistek** [comment] 2019-10-16 16:27
Hello @Leguark,

1) I made tests deleting all folders but I get even more errors because the setup script needs stuff that is in the folders.

2) I wrote directly to the scikit developers (I saw you also wrote two days ago but the unswer was a bit discouraging), to see if they have some suggestion.

3) I have WSL (Windows Subsystem fo Linux) on my PC. Maybe I can install GemPy there, under Linux, and see if it is better? The limitation is that WSL is a terminal-only system. In principle I can start Jupyter there, copy the token from the terminal, paste it in my browser in Windows, and see it running (it should be more or less the same as using Jupyter on a remote workstation). But what would happen to 3D windows opened for VTK?

Thanks!

**Comment by Leguark** [comment] 2019-10-17 07:45
Thank you for your research and support on the pull request!

I just merged all skimage last changes to my branch. I did not have time to test anything yet but maybe you can give it a try if you have time.

Regarding the point 3, I work a lot with jupyter remotely and you are right that vtk does not work. I hope that once we port it to vista since (in principle, having some problems there right now) it can render on the notebook itself via html, we will be able to see vtk also remotely.

**Comment by Leguark** [comment] 2019-10-18 07:22
Okay I just push that commit. Lets see if it fix it

**Comment by bistek** [comment] 2019-10-21 15:44
Dear @Leguark, something is OK, but I have new problems that I have never had before...

This is the story step by step:

1) I installed your scikit-image. All is OK here. Maybe you can update the installation instructions on the home page for this (at the moment it says to install the standard scikit-image).

2) I run the tutorials that were not running, like Ch1-1_Basics, ch1-6_CreatingModels, ch1-8_Onlap_relations, etc.. They are OK now. Very good news!

3) I went back to my model. The model was running before the update, with problems around faults, but the overall stratigraphy was OK. But now I have problems with it.  

3A) If I use `gp.compute_model(geo_model, compute_mesh=True, sort_surfaces=False)` (with or without  `sort_surfaces=False`), it runs for some time and then the kernel crashes.

3B) If I use `gp.compute_model(geo_model, compute_mesh=False, sort_surfaces=False)` (with or without  `sort_surfaces=False`), it runs for quite a long time and converges. However I still have problems with faults and particularly finite faults, probably since I am still using `compute_mesh=False`.

One problem I really do not understand is the following:

- If I use a smaller input dataset (called "5 sections" in the attached notebook) I have a poor resolution model, with some errors, but also with some areas properly modeled.

- If I use a larger input dataset (called "10 sections" in the attached notebook) I expect to obtain a higher resolution model, but actually I get a model with a stratigraphy that is completely messed up, with no single fault block that is OK (see cross sections in the notebook).

Do you have any idea? Maybe the fault network is too complicate? Actually, it is already really simplified with respect to the real geological situation, so it is really critical for me to see if I can model a situation with at least this level of complexity.

I attach the notebook and the input data.

[LPproject_from_ch1-1_Basics.zip](https://github.com/cgre-aachen/gempy/files/3751684/LPproject_from_ch1-1_Basics.zip)

[LP_input_data.zip](https://github.com/cgre-aachen/gempy/files/3751674/LP_input_data.zip)

Thanks very much!

**Closed** 2020-02-23 14:36 UTC
Labels: question
